# Generated by Django 2.2 on 2019-04-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190416_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
