# Generated by Django 2.2 on 2019-04-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
