# Generated by Django 2.2 on 2019-04-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
