# Generated by Django 2.2 on 2019-04-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_question_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='user_id',
        ),
    ]
