# Generated by Django 2.2 on 2019-04-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
